import type { Metadata } from "next";
import { CtaBand, PageHero, SectionHeading } from "@/components/ui";

export const metadata: Metadata = { title: "Quality", description: "NS Elevator quality-process and certification-verification framework.", alternates: { canonical: "/quality" } };

const stages = ["Requirements review", "Design coordination", "Incoming material control", "Production inspection", "Functional testing", "Handover records"];

export default function QualityPage() {
  return <><PageHero eyebrow="Quality framework" title="Evidence at every handoff." intro="Quality claims must be supported by documented processes, applicable standards, test records, and verified certificates—not marketing language alone." index="Quality / Owner verification required" /><section className="bg-[#11110f] py-20 text-white md:py-32"><div className="container-site"><SectionHeading inverse eyebrow="Process architecture" title="Control the interfaces. Record the result." text="The final quality plan must reflect actual NS Elevator procedures and each project's applicable jurisdiction." /><div className="mt-16 grid md:grid-cols-2 lg:grid-cols-3">{stages.map((stage, index) => <article key={stage} className="min-h-56 border-t border-white/20 p-6 md:border-r"><span className="text-[0.62rem] font-bold text-[#c98b53]">{String(index + 1).padStart(2, "0")}</span><h2 className="display mt-16 text-3xl">{stage}</h2><p className="mt-4 text-sm leading-6 text-white/50">Detailed inspection criteria and record templates pending verified quality documentation.</p></article>)}</div></div></section><section className="container-site py-20 md:py-32"><div className="grid gap-14 lg:grid-cols-[0.65fr_1.35fr]"><div><span className="eyebrow">Certification register</span><h2 className="display mt-8 text-5xl md:text-6xl">Nothing published without verification.</h2></div><div className="border-t border-[#a9663f]"><div className="bg-[#eadcd0] p-6"><p className="font-bold">No certificates have been supplied or verified.</p><p className="mt-3 text-sm leading-6 text-[#65635d]">Before launch, provide certificate files, issuing body, scope, identifier, issue date, expiry date, and written approval for publication.</p></div>{["Certification and standards", "Production testing", "Safety processes", "Downloadable evidence"].map((item) => <div key={item} className="flex items-center justify-between border-b hairline py-6"><span className="display text-2xl">{item}</span><span className="text-[0.62rem] font-bold tracking-[0.14em] text-[#8b8880] uppercase">Pending</span></div>)}</div></div></section><CtaBand title="Make quality traceable." /></>;
}
