import type { Metadata } from "next";
import { CtaBand, PageHero, SectionHeading } from "@/components/ui";
import { T } from "@/components/language-provider";

export const metadata: Metadata = { title: "Quality", description: "NS Elevator quality-process and certification-verification framework.", alternates: { canonical: "/quality" } };

const stages = ["Requirements review", "Design coordination", "Incoming material control", "Production inspection", "Functional testing", "Handover records"];
const stagesZh = ["需求评审", "设计协调", "来料控制", "生产检验", "功能测试", "交付记录"];
const registerItems = ["Certification and standards", "Production testing", "Safety processes", "Downloadable evidence"];
const registerItemsZh = ["认证与标准", "生产测试", "安全流程", "可下载证明资料"];

export default function QualityPage() {
  return <><PageHero eyebrow="Quality framework" eyebrowZh="质量框架" title="Evidence at every handoff." titleZh="每次交接都有证据。" intro="Quality claims must be supported by documented processes, applicable standards, test records, and verified certificates—not marketing language alone." introZh="质量主张必须由书面流程、适用标准、测试记录和经验证的证书支持，而不能仅依赖营销语言。" index="Quality / Owner verification required" indexZh="质量 / 需业主验证" /><section className="bg-[#11110f] py-20 text-white md:py-32"><div className="container-site"><SectionHeading inverse eyebrow="Process architecture" eyebrowZh="流程架构" title="Control the interfaces. Record the result." titleZh="控制每个接口，记录每项结果。" text="The final quality plan must reflect actual NS Elevator procedures and each project's applicable jurisdiction." textZh="最终质量计划必须反映 NS Elevator 的实际流程及每个项目适用的司法辖区要求。" /><div className="mt-16 grid md:grid-cols-2 lg:grid-cols-3">{stages.map((stage, index) => <article key={stage} className="min-h-56 border-t border-white/20 p-6 md:border-r"><span className="text-[0.62rem] font-bold text-[#c98b53]">{String(index + 1).padStart(2, "0")}</span><h2 className="display mt-16 text-3xl"><T en={stage} zh={stagesZh[index]} /></h2><p className="mt-4 text-sm leading-6 text-white/50"><T en="Detailed inspection criteria and record templates pending verified quality documentation." zh="详细检验标准与记录模板将在质量文件验证后发布。" /></p></article>)}</div></div></section><section className="container-site py-20 md:py-32"><div className="grid gap-14 lg:grid-cols-[0.65fr_1.35fr]"><div><span className="eyebrow"><T en="Certification register" zh="认证登记" /></span><h2 className="display mt-8 text-5xl md:text-6xl"><T en="Nothing published without verification." zh="未经验证，不予发布。" /></h2></div><div className="border-t border-[#a9663f]"><div className="bg-[#eadcd0] p-6"><p className="font-bold"><T en="No certificates have been supplied or verified." zh="目前尚未提供或验证任何证书。" /></p><p className="mt-3 text-sm leading-6 text-[#65635d]"><T en="Before launch, provide certificate files, issuing body, scope, identifier, issue date, expiry date, and written approval for publication." zh="正式发布前，请提供证书文件、颁发机构、适用范围、编号、签发日期、到期日期以及书面发布授权。" /></p></div>{registerItems.map((item, index) => <div key={item} className="flex items-center justify-between border-b hairline py-6"><span className="display text-2xl"><T en={item} zh={registerItemsZh[index]} /></span><span className="text-[0.62rem] font-bold tracking-[0.14em] text-[#8b8880] uppercase"><T en="Pending" zh="待提供" /></span></div>)}</div></div></section><CtaBand title="Make quality traceable." titleZh="让质量全程可追溯。" /></>;
}
