import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, ConceptLabel, CtaBand } from "@/components/ui";
import { T } from "@/components/language-provider";
import { getProject, projects } from "@/content/projects";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const item = getProject((await params).slug); return item ? { title: item.seoTitle, description: item.seoDescription, alternates: { canonical: `/projects/${item.slug}` } } : {}; }

export default async function ProjectDetail({ params }: Props) {
  const project = getProject((await params).slug); if (!project) notFound();
  return <><Breadcrumbs items={[{ label: "Home", labelZh: "首页", href: "/" }, { label: "Projects", labelZh: "项目", href: "/projects" }, { label: project.title, labelZh: project.zh.title }]} /><section className="container-site border-t hairline pt-10 pb-16"><div className="grid gap-12 lg:grid-cols-[1.3fr_0.7fr] lg:items-end"><div><p className="eyebrow"><T en="Unverified concept record" zh="未验证的概念案例" /></p><h1 className="display mt-9 text-[clamp(3.8rem,8vw,8.5rem)] leading-[0.84]"><T en={project.title} zh={project.zh.title} /></h1></div><div><p className="text-sm leading-7 text-[#64625c]"><T en={project.summary} zh={project.zh.summary} /></p><div className="mt-8 grid grid-cols-2 gap-5 border-t hairline pt-5 text-xs"><div><p className="font-bold uppercase tracking-[0.12em] text-[#88857d]"><T en="Location" zh="地点" /></p><p className="mt-2"><T en={`${project.city}, ${project.country}`} zh={`${project.zh.city}，${project.zh.country}`} /></p></div><div><p className="font-bold uppercase tracking-[0.12em] text-[#88857d]"><T en="Building" zh="建筑类型" /></p><p className="mt-2"><T en={project.buildingType} zh={project.zh.buildingType} /></p></div></div></div></div></section><section className="container-site"><div className="relative aspect-[16/8] overflow-hidden"><ConceptLabel /><Image src={project.images[0].src} alt={project.images[0].alt} fill sizes="100vw" className="object-cover" /></div><p className="mt-3 text-xs text-[#77746d]"><T en={project.images[0].caption} zh="概念项目效果图；不代表已完成的真实项目。" /></p></section><section className="container-site grid gap-16 py-20 md:py-32 lg:grid-cols-[0.7fr_1.3fr]"><div><span className="eyebrow"><T en="Record status" zh="案例状态" /></span><h2 className="display mt-8 text-5xl"><T en="Awaiting verified project data." zh="等待经验证的项目资料。" /></h2></div><div><p className="display text-3xl leading-tight"><T en={project.description} zh={project.zh.description} /></p><div className="mt-12 border-t hairline"><div className="grid grid-cols-2 border-b hairline py-5 text-sm"><span className="text-[#77746d]"><T en="Elevator types" zh="电梯类型" /></span><span><T en={project.elevatorTypes.join(", ")} zh={project.zh.elevatorTypes.join("、")} /></span></div><div className="grid grid-cols-2 border-b hairline py-5 text-sm"><span className="text-[#77746d]"><T en="Completion year" zh="完成年份" /></span><span><T en="Pending verification" zh="待验证" /></span></div><div className="grid grid-cols-2 border-b hairline py-5 text-sm"><span className="text-[#77746d]"><T en="Client approval" zh="客户授权" /></span><span><T en="Not supplied" zh="尚未提供" /></span></div></div><Link href="/contact" className="button-dark mt-10"><T en="Discuss a similar brief" zh="咨询类似项目" /> <span aria-hidden="true">↗</span></Link></div></section><CtaBand /></>;
}
